### ISSUE TITLE
Template errors when using f64 inputs for training

### ISSUE THREAD

**Issue by fabiokr** [elixir-nx/axon#494] opened 2023-05-23 23:02 UTC
I'm still learning Axon and machine learning in general, so this is probably a mistake on my end, but I'm hitting a wall and I'm not sure where to look next. I'm playing with trying to predict a value from some input values. I have the following livebook setup: https://gist.github.com/fabiokr/3938a5bebd06ebe2ba8ecea2af687573. 

On the last step *Training the model*, I get the following error:

```
** (ArgumentError) argument at position 3 is not compatible with compiled function template.

Expected template:

#Nx.Tensor<
  f32
  Nx.TemplateBackend
>

Argument template:

#Nx.Tensor<
  f64
  Nx.TemplateBackend
>

```

I'm not sure how to read the error message and come up with what is wrong. It looks like somewhere it expects an f32 tensor, but get an f64 one. In the livebook, I have some code to normalize values so they are in between 0 and 1 (floats), but I don't know what exactly is wrong.

Any directions on what could I be missing?

**Comment by seanmor5** [comment] 2023-05-24 00:05
Can you check your input data type? Is it an f64? If so, that's likely the source of the error. Axon assumes f32 in a lot of places and so the mismatch might come from accidentally downcasting

**Comment by fabiokr** [comment] 2023-05-24 00:38
@seanmor5 This is an example DataFrame:

![image](https://github.com/elixir-nx/axon/assets/21800/ace5bc67-3358-4297-b5bf-33b01ed90a66)

What would I need to do to convert?

**Comment by fabiokr** [comment] 2023-05-24 13:32
@josevalim That fixed it, thank you! https://gist.github.com/fabiokr/3938a5bebd06ebe2ba8ecea2af687573/revisions#diff-a694c3393e7c670d10b512bf0802e5836fb9f13f6ea63198c2a901f4a791f899R178

I was following along the Axon credit card fraud guide https://hexdocs.pm/axon/credit_card_fraud.html, and it didn't look like it ever had to do that cast with `Nx.as_type`. I'm wondering if it has something to do with the way I am transforming the data? https://gist.github.com/fabiokr/3938a5bebd06ebe2ba8ecea2af687573/revisions#diff-a694c3393e7c670d10b512bf0802e5836fb9f13f6ea63198c2a901f4a791f899R70

Thanks anyway!

**Comment by seanmor5** [comment] 2023-05-24 14:01
I will leave this open until I can figure out why Axon isn't working with f64 inputs. In any case, you should prefer f32 almost always as it will be much faster with XLA. But, it should not raise mismatch errors

**Comment by josevalim** [comment] 2023-05-24 15:14
@seanmor5 we always compile it based on the Axon.input instead of what the user actually gives, so it looks like the correct behaviour to me?

**Comment by seanmor5** [comment] 2023-05-24 23:46
Nope, the Axon.input has no impact on the compiled shape. So even if you provide shape/type it will be ignored. It's based on the provided shape instead

**Comment by seanmor5** [comment] 2023-06-03 16:22
I cannot seem to reproduce the template errors with f64 inputs on main. I'm closing for now

**Closed by seanmor5** 2023-06-03 16:22 UTC
