### ISSUE TITLE
Req usage in OTP 26

### ISSUE THREAD

**Issue by mwhitworth** [elixir-nx/axon#570] opened 2024-05-08 11:02 UTC
With the release of OTP 26, the client default `verify` option is now `:verify_peer`. ([ref](https://www.erlang.org/news/164#ssl)), which breaks `Req` downloads by default with certificate verification errors

To ensure that the examples in the documentation continue to work, there are two options:
1. use libraries like [tls_certificate_check](https://hex.pm/packages/tls_certificate_check) to make it easy to establish more secure HTTPS connections regardless of OTP version:
```elixir
book_text = Req.get!("example.com", connect_options: [transport_opts: tls_certificate_check:options('example.com')]).body
```

2. set request transport options to `:verify_none`, to restore the previous behaviour of skipping SSL certificate verification (by default)

I'm happy to implement either, but perhaps this has been solved elsewhere or with global defaults.

**Comment by wojtekmach** [comment] 2024-05-08 11:24
Could you check on latest Req? Maybe it’s a matter of loosening up version requirement, eg:

https://github.com/elixir-nx/axon/blob/main/examples/generative/text_generator.exs#L6

Is not picking the latest version.

**Comment by mwhitworth** [comment] 2024-05-08 13:20
```elixir
iex> Application.spec(:req, :vsn)
~c"0.4.14"
iex> Req.get!("https://www.gutenberg.org").body
** (Mint.TransportError) TLS client: In state wait_cert_cr at ssl_handshake.erl:2126 generated CLIENT ALERT: Fatal - Bad Certificate
```

though curiously `https://www.example.com` works in this example without additional options.

**Comment by wojtekmach** [comment] 2024-05-08 13:38
Thanks, I can reproduce this locally, I will look into it.

**Comment by wojtekmach** [comment] 2024-05-09 13:31
Per https://github.com/erlang/otp/issues/8466#issuecomment-2102641396

> I noticed that the problem with the cert chain is that it has one cert that uses sha (sha1) in its signature algorithm and that is no longer supported by default.

It is marked as "not a bug" in OTP

Anyway, I could use this with Req and I got a successful response:

```elixir
iex> options = [transport_opts: [signature_algs_cert: :ssl.signature_algs(:default, :"tlsv1.3") ++ [sha: :rsa]]]
iex> Req.get!("https://www.gutenberg.org", connect_options: options)
```

I am not sure what is the best path forward for Axon.

FWIW Req has a checksum feature so you can use that along with `verify: :verify_none`:

```
iex> options = [transport_opts: [verify: :verify_none]]
iex> Req.get!("https://www.gutenberg.org", connect_options: options, checksum: "md5:5f72f1f7bdee16a64e26b46cf2e7c40f")
```

**Comment by mwhitworth** [comment] 2024-05-10 14:18
> I am not sure what is the best path forward for Axon.

IMO, extending the first example quoted. We can view it as "configuration" for now and place the `options` variable at the head of each notebook. Then passing it to `Req.get!` calls seems like a reasonable way to go - as secure, functional and clear as possible for all OTP versions until the `gutenberg.org` certificate chain is updated.

**Closed** 2024-05-14 12:30 UTC
