### ISSUE TITLE
Issues running mnist examples.

### ISSUE THREAD

**Issue by konstantinzolotarev** [elixir-nx/axon#73] opened 2021-06-08 12:16 UTC
Trying to evaluate `examples/mnist.exs` or `notebooks/mnist.livemd` fails on last (training) step with error.

Environment was just installed:

MacBook Pro (16-inch, 2019) Intel based.

```
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit] [dtrace]
Elixir 1.12.1 (compiled with Erlang/OTP 24)
Livebook 0.1.2
```

`examples/mnist.exs` output: 

```elixir
--------------------------------------------------
                      Model
==================================================
 Layer                    Shape        Parameters
==================================================
 input_7 ( input )        {nil, 784}   0
 dense_10 ( dense )       {nil, 128}   100480
 relu_11 ( relu )         {nil, 128}   0
 dropout_12 ( dropout )   {nil, 128}   0
 dense_15 ( dense )       {nil, 10}    1290
 softmax_16 ( softmax )   {nil, 10}    0
--------------------------------------------------


15:04:33.745 [info]  XLA service 0x7f855952ee20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:

15:04:33.745 [info]    StreamExecutor device (0): Host, Default Version
** (ArgumentError) expected a %Nx.Tensor{} or a number, got: {32, 128}
    (nx 0.1.0-dev) lib/nx.ex:1170: Nx.to_tensor/1
    (nx 0.1.0-dev) lib/nx.ex:2561: Nx.element_wise_pred_op/3
    (axon 0.1.0-dev) lib/axon/layers.ex:1098: anonymous fn/1 in Axon.Layers."__defn:dropout__"/2
    (axon 0.1.0-dev) lib/axon/layers.ex:1095: Axon.Layers."__defn:dropout__"/2
    (axon 0.1.0-dev) lib/axon/compiler.ex:218: anonymous fn/7 in Axon.Compiler.recur_predict_fun/3
    (axon 0.1.0-dev) lib/axon/compiler.ex:196: anonymous fn/4 in Axon.Compiler.recur_predict_fun/3
    (axon 0.1.0-dev) lib/axon/training.ex:133: anonymous fn/6 in Axon.Training.step/4
    (nx 0.1.0-dev) lib/nx/defn/grad.ex:15: Nx.Defn.Grad.transform/3
```

`notebooks/mnist.livemd` output: 

```elixir
** (ArgumentError) expected a %Nx.Tensor{} or a number, got: {32, 10}
    (nx 0.1.0-dev) lib/nx.ex:1170: Nx.to_tensor/1
    (nx 0.1.0-dev) lib/nx.ex:2561: Nx.element_wise_pred_op/3
    (axon 0.1.0-dev) lib/axon/shared.ex:21: anonymous fn/1 in Axon.Shared."__defn:assert_shape!__"/2
    (nx 0.1.0-dev) lib/nx/defn/compiler.ex:307: Nx.Defn.Compiler.__remote__/4
    (axon 0.1.0-dev) lib/axon/losses.ex:164: Axon.Losses."__defn:categorical_cross_entropy__"/3
    (axon 0.1.0-dev) lib/axon/training.ex:134: anonymous fn/6 in Axon.Training.step/4
    (nx 0.1.0-dev) lib/nx/defn/grad.ex:15: Nx.Defn.Grad.transform/3
    (axon 0.1.0-dev) lib/axon/training.ex:80: anonymous fn/7 in Axon.Training.step/3
```

**Comment by josevalim** [comment] 2021-06-09 10:50
@seanmor5 i have been thinking about this (and tests), and I think very simple tests where we can train a model with a very small batch and then predict, without really checking the result, would already go a long way to check that at least the whole model builds. :)

**Comment by seanmor5** [comment] 2021-06-10 00:19
Hi @konstantinzolotarev, you are running this with Axon master right? I am unable to reproduce this error.

@josevalim I agree, I will add integration tests to issue #45

**Comment by konstantinzolotarev** [comment] 2021-06-10 11:31
@seanmor5 Yep used code from commit `ec28a63744ea3caf3f2ddc10fbdd491508465d73`.

Tried with last one as well and still have same issue. 
I did a little bit more tests and found that issue is in such check for me: 
`transform(Nx.shape(mask) == Nx.shape(input), &IO.inspect/1)` 

As well as 
`{32, 128} == {32, 128}` inside `defn` function. 

Might be it will be helpful

**Comment by konstantinzolotarev** [comment] 2021-06-10 11:44
Furthermore it seems to be caused by latest commit in `nx` repo. 
https://github.com/elixir-nx/nx/commit/a6c9230f27af9160a039795364b9bb959c39b9da#

Because of

```
def left == right when Kernel.and(is_number(left), is_number(right)),
    do: Kernel.==(left, right)

  def left == right, do: Nx.equal(left, right)
``` 

And input structs are not numbers so it's jumps into `Nx.equal(left, right)` that requires input types to be tensors or numbers.

**Comment by josevalim** [comment] 2021-06-10 12:18
I think Nx is correct. We shouldn't be expecting comparison to work for anything besides tensors inside Nx. It is just that the transform gets the new scope too, and that can be confusing. Unless @seanmor5 wants to revert the `==` behaviour... but i don't he does. :)

**Comment by josevalim** [comment] 2021-06-10 12:24
I documented the problem here: https://github.com/elixir-nx/nx/blob/main/nx/lib/nx/defn/kernel.ex#L159

**Comment by konstantinzolotarev** [comment] 2021-06-11 09:13
@josevalim @seanmor5 May be it does make sense to add `Nx.Shape.equal?/2` function for tensors shape comparison ?

**Comment by seanmor5** [comment] 2021-06-13 00:54
@konstantinzolotarev This should be fixed with my most recent commit! Sorry it took so long to get this addressed

**Closed by seanmor5** 2021-06-13 00:54 UTC
